  name: project_ta
  description: "A new Flutter project."
  publish_to: 'none'
  version: 0.1.0

  environment:
    sdk: '>=3.2.0 <4.0.0'

  dependencies:
    flutter:
      sdk: flutter 
    get:
    flutter_svg:
    google_fonts:
    shared_preferences: ^2.2.3
    intl:
    http:
    animated_splash_screen: ^1.3.0
    persistent_bottom_nav_bar:
    shimmer:
    image_picker: ^1.1.2
    pinput:
    flutter_localization: ^0.2.0

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^2.0.0

  flutter:
    uses-material-design: true

    assets:
      - Assets/
